### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/NotEnoughAnimations#46]
java.lang.NullPointerException: Cannot read field "bgR" because "io.github.a5b84.darkloadingscreen.Mod.config" is null
	at net.minecraft.class_1041.redirect$bdb000$onCreateCapabilities(class_1041.java:1062)
	at net.minecraft.class_1041.<init>(class_1041.java:108)
	at net.minecraft.class_3682.method_16038(class_3682.java:21)
	at net.minecraft.class_310.<init>(class_310.java:481)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by tr7zw** [comment]
``Cannot read field "bgR" because "io.github.a5b84.darkloadingscreen.Mod.config" is null``
This mod has nothing to do with darkloadingscreen, so maybe it's the wrong crash report?
Also you have to make sure to update notenoughanimations and TRansliterationLib at the same time(or use the newest of both).
