### ISSUE TITLE
SetupAnimEnd needs a player check due to FancyMenu

### ISSUE THREAD

**Issue by Fefedu973** [tr7zw/NotEnoughAnimations#94]
this mod is not compatible with fancy menu
java.lang.ClassCastException: class de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerEntity cannot be cast to class net.minecraft.class_742 (de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerEntity and net.minecraft.class_742 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2473b9ce)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_591.handler$coo000$setupAnimEnd(class_591.java:540)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_591.method_17087(class_591.java:179)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_591.method_2819(class_591.java:22)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_922.method_4054(class_922.java:129)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerRenderer.render(PlayerEntityCustomizationItem.java:453)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderEntityStatic(PlayerEntityCustomizationItem.java:317)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.lambda$renderPlayerEntity$0(PlayerEntityCustomizationItem.java:292)
[17:47:35] [Render thread/INFO]: [STDERR]:     at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderPlayerEntity(PlayerEntityCustomizationItem.java:291)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.render(PlayerEntityCustomizationItem.java:236)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.menuhandler.MenuHandlerBase.onRenderPost(MenuHandlerBase.java:1246)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.MainMenuHandler.onRenderPost(MainMenuHandler.java:117)
[17:47:35] [Render thread/INFO]: [STDERR]:     at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
[17:47:35] [Render thread/INFO]: [STDERR]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:47:35] [Render thread/INFO]: [STDERR]:     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.konkrete.events.EventHandler.invokeEvent(EventHandler.java:115)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.konkrete.events.EventHandler.callEventsFor(EventHandler.java:102)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_757.handler$ccm000$beforeRenderScreen(class_757.java:6047)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_757.method_3192(class_757.java:877)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_310.method_1523(class_310.java:1122)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_310.method_1514(class_310.java:737)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.client.main.Main.main(Main.java:236)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Fefedu973** [comment]
no when 3d layer is installed the player model of fancy menu not working
is there a way to add an option to disable 3d layer when is it not in game

**Comment by tr7zw** [comment]
Like I said, that log is because of NotEnoughAnimations, not 3d Skin Layers.
![grafik](https://user-images.githubusercontent.com/5133936/171929519-a9b58ceb-81ba-4028-9ca8-34e2d6df1746.png)
3d Skin layers works exactly like without it(no skin, but it renders).

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/171930782-f250b4ad-60b4-45c0-8225-52d90371a541.png)
Managed to load a skin with 3d skin layers mod installed, they render in 2d because of how screwed up that model gets rendered(FancyMenu should redo this logic IMO), but it does 100% work.

**Comment by Fefedu973** [comment]
> ![grafik](https://user-images.githubusercontent.com/5133936/171930782-f250b4ad-60b4-45c0-8225-52d90371a541.png) Managed to load a skin with 3d skin layers mod installed, they render in 2d because of how screwed up that model gets rendered(FancyMenu should redo this logic IMO), but it does 100% work.
I have retested and it works but it spam the console and yes the problem come from not enough animation BUT with 3d skin layer the pseudo and the parrot dont show

**Comment by Fefedu973** [comment]
and the console is spam
![image](https://user-images.githubusercontent.com/80718477/171983622-0eed69cf-06fa-43d7-bdb3-ac1773137555.png)

**Comment by Fefedu973** [comment]
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_19538()" because "$$0" is null
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.minecraft.class_1297.method_5858(class_1297.java:1414)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.minecraft.class_976.handler$dfb001$render(class_976.java:541)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.minecraft.class_976.method_17159(class_976.java)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.minecraft.class_976.method_4199(class_976.java:33)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.minecraft.class_922.method_4054(class_922.java:145)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerRenderer.render(PlayerEntityCustomizationItem.java:453)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderEntityStatic(PlayerEntityCustomizationItem.java:319)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.lambda$renderPlayerEntity$0(PlayerEntityCustomizationItem.java:292)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderPlayerEntity(PlayerEntityCustomizationItem.java:291)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.render(PlayerEntityCustomizationItem.java:236)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.helper.layoutcreator.content.LayoutElement.render(LayoutElement.java:690)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.helper.layoutcreator.LayoutEditorScreen.method_25394(LayoutEditorScreen.java:555)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.helper.layoutcreator.PreloadedLayoutEditorScreen.method_25394(PreloadedLayoutEditorScreen.java:872)
06:49:01.455
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:877)
06:49:01.456
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1122)
06:49:01.456
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
06:49:01.456
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
06:49:01.456
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
06:49:01.456
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
06:49:01.456
net.minecraft.class_2983
Render thread
[STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Fefedu973** [comment]
Fixed by fancy menu mod

**Comment by tr7zw** [comment]
OK then I'll take your word for it.
